server:
  port: 8000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amp-news/amp-configs.git
          username: ${config.server.git.username}
          password: ${config.server.git.pass}
          clone-on-start: true